from pathlib import Path
import calendar

import numpy as np
import pandas as pd
import geopandas as gpd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st
from scipy.stats import linregress, theilslopes

# ============================================================
# PAGE CONFIGURATION
# ============================================================
st.set_page_config(
    page_title="Thailand GRACE TWSA DSS FALI ANI",
    page_icon="💧",
    layout="wide",
)

DATA_DIR = Path(__file__).resolve().parent / "data"

NATIONAL_FILE = DATA_DIR / "Thailand_National_GRACE_TimeSeries_CompleteTimeline.csv"
BASIN_FILE = DATA_DIR / "Thailand_22_Basins_Complete_Monthly_Timeline.csv"
TREND_FILE = DATA_DIR / "Thailand_22_Basins_TWSA_Trend_Results.csv"
CLIM_FILE = DATA_DIR / "Thailand_22_Basins_Monthly_TWSA_Climatology.csv"
SEASONAL_FILE = DATA_DIR / "Thailand_22_Basins_Seasonal_TWSA_Summary.csv"
BASIN_GPKG = DATA_DIR / "Thailand_22_Principal_Basins.gpkg"

REQUIRED_FILES = [
    NATIONAL_FILE,
    BASIN_FILE,
    TREND_FILE,
    CLIM_FILE,
    SEASONAL_FILE,
    BASIN_GPKG,
]


def stop_if_files_missing():
    missing = [path.name for path in REQUIRED_FILES if not path.exists()]
    if missing:
        st.error(
            "The app cannot start because these required files are missing from the data folder:\n\n"
            + "\n".join(f"- {name}" for name in missing)
        )
        st.stop()


def normalize_basin_code(series: pd.Series) -> pd.Series:
    """Normalize basin codes so 1 becomes 01 and 21.0 becomes 21."""
    return (
        series.astype(str)
        .str.strip()
        .str.replace(r"\.0$", "", regex=True)
        .str.zfill(2)
    )


def require_columns(df: pd.DataFrame, required: list[str], label: str):
    missing = [column for column in required if column not in df.columns]
    if missing:
        st.error(
            f"{label} is missing expected columns: {', '.join(missing)}. "
            "Please confirm that this file was generated by the revised Objective 1 notebook."
        )
        st.stop()


stop_if_files_missing()


# ============================================================
# DATA LOADING
# ============================================================
@st.cache_data(show_spinner=False)
def load_data():
    national = pd.read_csv(NATIONAL_FILE)
    basin = pd.read_csv(BASIN_FILE)
    trend = pd.read_csv(TREND_FILE)
    climatology = pd.read_csv(CLIM_FILE)
    seasonal = pd.read_csv(SEASONAL_FILE)
    basin_gdf = gpd.read_file(BASIN_GPKG, engine="pyogrio")

    require_columns(
        national,
        ["month_date", "mean_twsa"],
        NATIONAL_FILE.name,
    )
    require_columns(
        basin,
        ["MB_CODE", "MBASIN_E", "month_date", "twsa_cm"],
        BASIN_FILE.name,
    )
    require_columns(
        trend,
        [
            "MB_CODE",
            "MBASIN_E",
            "sen_slope_cm_per_year",
            "sen_slope_mm_per_year",
            "mann_kendall_p_value",
            "mann_kendall_trend",
        ],
        TREND_FILE.name,
    )
    require_columns(
        climatology,
        [
            "MB_CODE",
            "MBASIN_E",
            "calendar_month",
            "mean_twsa_cm",
        ],
        CLIM_FILE.name,
    )
    require_columns(
        seasonal,
        [
            "MB_CODE",
            "MBASIN_E",
            "highest_storage_month",
            "highest_mean_twsa_cm",
            "lowest_storage_month",
            "lowest_mean_twsa_cm",
            "seasonal_amplitude_cm",
        ],
        SEASONAL_FILE.name,
    )
    require_columns(
        basin_gdf,
        ["MB_CODE", "MBASIN_E", "geometry"],
        BASIN_GPKG.name,
    )

    # Dates
    national["month_date"] = pd.to_datetime(national["month_date"], errors="coerce")
    basin["month_date"] = pd.to_datetime(basin["month_date"], errors="coerce")

    # Basin codes
    for frame in [basin, trend, climatology, seasonal]:
        frame["MB_CODE"] = normalize_basin_code(frame["MB_CODE"])

    basin_gdf["MB_CODE"] = normalize_basin_code(basin_gdf["MB_CODE"])

    # Numeric fields
    national_numeric = [
        "mean_twsa",
        "median_twsa",
        "std_twsa",
        "min_twsa",
        "max_twsa",
        "moving_average_12m",
        "linear_trend",
    ]
    for column in national_numeric:
        if column in national.columns:
            national[column] = pd.to_numeric(national[column], errors="coerce")

    basin_numeric = ["twsa_cm", "moving_average_12m_cm", "valid_pixels"]
    for column in basin_numeric:
        if column in basin.columns:
            basin[column] = pd.to_numeric(basin[column], errors="coerce")

    trend_numeric = [
        "number_of_observations",
        "ols_slope_cm_per_year",
        "ols_slope_mm_per_year",
        "ols_p_value",
        "ols_r_squared",
        "mann_kendall_p_value",
        "mann_kendall_tau",
        "sen_slope_cm_per_year",
        "sen_slope_mm_per_year",
        "sen_lower_cm_per_year",
        "sen_upper_cm_per_year",
    ]
    for column in trend_numeric:
        if column in trend.columns:
            trend[column] = pd.to_numeric(trend[column], errors="coerce")

    clim_numeric = [
        "calendar_month",
        "mean_twsa_cm",
        "median_twsa_cm",
        "standard_deviation_cm",
        "number_of_observations",
    ]
    for column in clim_numeric:
        if column in climatology.columns:
            climatology[column] = pd.to_numeric(climatology[column], errors="coerce")

    seasonal_numeric = [
        "highest_mean_twsa_cm",
        "lowest_mean_twsa_cm",
        "seasonal_amplitude_cm",
    ]
    for column in seasonal_numeric:
        if column in seasonal.columns:
            seasonal[column] = pd.to_numeric(seasonal[column], errors="coerce")

    # Map geometry in geographic coordinates
    if basin_gdf.crs is None:
        st.error("The basin GeoPackage has no CRS information.")
        st.stop()

    basin_gdf = basin_gdf.to_crs("EPSG:4326")

    national = national.sort_values("month_date").reset_index(drop=True)
    basin = basin.sort_values(["MB_CODE", "month_date"]).reset_index(drop=True)
    trend = trend.sort_values("sen_slope_cm_per_year").reset_index(drop=True)
    climatology = climatology.sort_values(["MB_CODE", "calendar_month"]).reset_index(drop=True)

    return national, basin, trend, climatology, seasonal, basin_gdf


national_df, basin_df, trend_df, clim_df, seasonal_df, basin_gdf = load_data()


# ============================================================
# HELPER FUNCTIONS
# ============================================================
def get_location_series(location_code: str) -> pd.DataFrame:
    if location_code == "NATIONAL":
        frame = national_df.copy()
        frame = frame.rename(
            columns={
                "mean_twsa": "twsa_cm",
                "moving_average_12m": "moving_average_12m_cm",
            }
        )
        return frame.sort_values("month_date")

    return (
        basin_df.loc[basin_df["MB_CODE"] == location_code]
        .copy()
        .sort_values("month_date")
    )


def calculate_series_statistics(series: pd.DataFrame):
    observed = (
        series.dropna(subset=["month_date", "twsa_cm"])
        .sort_values("month_date")
        .copy()
    )

    if len(observed) < 3:
        return None

    elapsed_years = (
        observed["month_date"] - observed["month_date"].min()
    ).dt.days / 365.2425

    ols = linregress(elapsed_years, observed["twsa_cm"])
    sen = theilslopes(observed["twsa_cm"], elapsed_years, alpha=0.95)

    monthly_climatology = (
        observed.assign(calendar_month=observed["month_date"].dt.month)
        .groupby("calendar_month")["twsa_cm"]
        .mean()
    )

    minimum_row = observed.loc[observed["twsa_cm"].idxmin()]
    maximum_row = observed.loc[observed["twsa_cm"].idxmax()]

    return {
        "observations": int(len(observed)),
        "missing_months": int(series["twsa_cm"].isna().sum()),
        "mean": float(observed["twsa_cm"].mean()),
        "minimum": float(minimum_row["twsa_cm"]),
        "minimum_date": minimum_row["month_date"],
        "maximum": float(maximum_row["twsa_cm"]),
        "maximum_date": maximum_row["month_date"],
        "ols_slope": float(ols.slope),
        "ols_p_value": float(ols.pvalue),
        "ols_r_squared": float(ols.rvalue ** 2),
        "sen_slope": float(sen.slope),
        "sen_lower": float(sen.low_slope),
        "sen_upper": float(sen.high_slope),
        "seasonal_amplitude": float(monthly_climatology.max() - monthly_climatology.min()),
    }


def make_time_series_figure(series: pd.DataFrame, title: str):
    figure = go.Figure()

    figure.add_trace(
        go.Scatter(
            x=series["month_date"],
            y=series["twsa_cm"],
            mode="lines+markers",
            name="Monthly TWSA",
            connectgaps=False,
            marker={"size": 4},
        )
    )

    if "moving_average_12m_cm" in series.columns:
        figure.add_trace(
            go.Scatter(
                x=series["month_date"],
                y=series["moving_average_12m_cm"],
                mode="lines",
                name="12-month moving average",
                connectgaps=False,
            )
        )

    # National CSV already contains the preliminary OLS line produced by the notebook.
    if "linear_trend" in series.columns and series["linear_trend"].notna().any():
        figure.add_trace(
            go.Scatter(
                x=series["month_date"],
                y=series["linear_trend"],
                mode="lines",
                name="Linear trend",
                connectgaps=False,
                line={"dash": "dash"},
            )
        )

    figure.add_hline(y=0, line_dash="dash")
    figure.update_layout(
        title=title,
        xaxis_title="Date",
        yaxis_title="TWSA (cm)",
        height=520,
        hovermode="x unified",
        legend_title_text="",
    )

    return figure


def csv_bytes(frame: pd.DataFrame) -> bytes:
    return frame.to_csv(index=False).encode("utf-8")


# ============================================================
# HEADER
# ============================================================
st.title("💧 Thailand GRACE/GRACE-FO Water Storage DSS")
st.caption(
    "Objective 1 — Spatial and temporal characterization of terrestrial water storage anomalies across Thailand"
)

st.info(
    "Missing GRACE/GRACE-FO months are preserved as missing. The dashboard does not interpolate or fill mission gaps."
)


# ============================================================
# SIDEBAR LOCATION SELECTOR
# ============================================================
basin_options = (
    basin_df[["MB_CODE", "MBASIN_E"]]
    .drop_duplicates()
    .sort_values("MB_CODE")
    .reset_index(drop=True)
)

location_labels = ["Thailand national level"] + [
    f"{row.MB_CODE} — {row.MBASIN_E}"
    for row in basin_options.itertuples(index=False)
]

label_to_code = {"Thailand national level": "NATIONAL"}
for row in basin_options.itertuples(index=False):
    label_to_code[f"{row.MB_CODE} — {row.MBASIN_E}"] = row.MB_CODE

st.sidebar.header("Explore Objective 1")
selected_label = st.sidebar.selectbox("Location", location_labels)
selected_code = label_to_code[selected_label]
selected_name = (
    "Thailand national level"
    if selected_code == "NATIONAL"
    else selected_label.split(" — ", 1)[1]
)

selected_series = get_location_series(selected_code)
series_stats = calculate_series_statistics(selected_series)

st.sidebar.markdown("---")
st.sidebar.caption(
    "GRACE / GRACE-FO TWSA • Whole Thailand • 22 principal river basins"
)


# ============================================================
# TABS
# ============================================================
tab_dashboard, tab_map, tab_season, tab_trend, tab_data = st.tabs(
    [
        "📈 Dashboard",
        "🗺️ Monthly Basin Map",
        "🌦️ Seasonal Cycle",
        "📉 Trend Analysis",
        "⬇️ Data",
    ]
)


# ============================================================
# TAB 1 — DASHBOARD
# ============================================================
with tab_dashboard:
    st.subheader(selected_name)

    if selected_code == "NATIONAL":
        st.warning(
            "The national series is the preliminary domain-wide mean saved by the Objective 1 notebook. "
            "Your notebook notes that this series may include raster cells outside the Thailand land mask. "
            "Use the 22-basin polygon results for the current spatially constrained basin analysis until a final "
            "Thailand-masked national series is produced."
        )

    if series_stats is None:
        st.warning("Insufficient observed data for this location.")
    else:
        col1, col2, col3, col4 = st.columns(4)
        col1.metric("Observed months", f"{series_stats['observations']}")
        col2.metric("Missing months", f"{series_stats['missing_months']}")
        col3.metric("Mean TWSA", f"{series_stats['mean']:.2f} cm")
        col4.metric("Seasonal amplitude", f"{series_stats['seasonal_amplitude']:.2f} cm")

        time_figure = make_time_series_figure(
            selected_series,
            f"GRACE/GRACE-FO TWSA — {selected_name}",
        )
        st.plotly_chart(time_figure, use_container_width=True)

        left, right = st.columns(2)
        with left:
            st.markdown("#### Storage extremes")
            extremes = pd.DataFrame(
                {
                    "Statistic": ["Minimum TWSA", "Maximum TWSA"],
                    "Value": [
                        f"{series_stats['minimum']:.3f} cm",
                        f"{series_stats['maximum']:.3f} cm",
                    ],
                    "Month": [
                        series_stats["minimum_date"].strftime("%B %Y"),
                        series_stats["maximum_date"].strftime("%B %Y"),
                    ],
                }
            )
            st.dataframe(extremes, use_container_width=True, hide_index=True)

        with right:
            st.markdown("#### Descriptive trend summary")
            trend_summary = pd.DataFrame(
                {
                    "Statistic": [
                        "OLS slope",
                        "OLS p-value",
                        "OLS R²",
                        "Theil-Sen slope",
                        "Theil-Sen 95% interval",
                    ],
                    "Value": [
                        f"{series_stats['ols_slope']:.4f} cm/year",
                        f"{series_stats['ols_p_value']:.4g}",
                        f"{series_stats['ols_r_squared']:.3f}",
                        f"{series_stats['sen_slope']:.4f} cm/year",
                        f"{series_stats['sen_lower']:.4f} to {series_stats['sen_upper']:.4f} cm/year",
                    ],
                }
            )
            st.dataframe(trend_summary, use_container_width=True, hide_index=True)

        if selected_code != "NATIONAL":
            basin_trend_row = trend_df.loc[trend_df["MB_CODE"] == selected_code]
            if not basin_trend_row.empty:
                row = basin_trend_row.iloc[0]
                st.markdown("#### Formal basin trend result from Objective 1")
                c1, c2, c3, c4 = st.columns(4)
                c1.metric("Sen's slope", f"{row['sen_slope_mm_per_year']:.2f} mm/year")
                c2.metric("Mann-Kendall trend", str(row["mann_kendall_trend"]).title())
                c3.metric("MK p-value", f"{row['mann_kendall_p_value']:.4g}")
                c4.metric(
                    "Significant at 5%",
                    "Yes" if row["mann_kendall_p_value"] < 0.05 else "No",
                )


# ============================================================
# TAB 2 — MONTHLY BASIN MAP
# ============================================================
with tab_map:
    st.subheader("Monthly TWSA across Thailand's 22 principal river basins")

    observed_months = sorted(
        basin_df.loc[basin_df["twsa_cm"].notna(), "month_date"]
        .dropna()
        .drop_duplicates()
        .tolist()
    )

    if not observed_months:
        st.warning("No observed basin months were found.")
    else:
        selected_month = st.selectbox(
            "GRACE/GRACE-FO month",
            observed_months,
            index=len(observed_months) - 1,
            format_func=lambda value: pd.Timestamp(value).strftime("%B %Y"),
        )

        month_values = (
            basin_df.loc[
                basin_df["month_date"] == pd.Timestamp(selected_month),
                ["MB_CODE", "MBASIN_E", "twsa_cm"],
            ]
            .drop_duplicates("MB_CODE")
            .copy()
        )

        map_frame = basin_gdf[["MB_CODE", "MBASIN_E", "geometry"]].copy()
        map_frame = map_frame.merge(
            month_values[["MB_CODE", "twsa_cm"]],
            on="MB_CODE",
            how="left",
        )

        geojson = map_frame.__geo_interface__

        map_figure = px.choropleth(
            map_frame,
            geojson=geojson,
            locations="MB_CODE",
            featureidkey="properties.MB_CODE",
            color="twsa_cm",
            hover_name="MBASIN_E",
            hover_data={"MB_CODE": True, "twsa_cm": ":.3f"},
            color_continuous_midpoint=0,
            labels={"twsa_cm": "TWSA (cm)", "MB_CODE": "Basin code"},
            title=f"Basin-mean GRACE/GRACE-FO TWSA — {pd.Timestamp(selected_month):%B %Y}",
        )
        map_figure.update_geos(fitbounds="locations", visible=False)
        map_figure.update_layout(height=700, margin={"r": 0, "t": 60, "l": 0, "b": 0})
        st.plotly_chart(map_figure, use_container_width=True)

        observed_map_values = month_values.dropna(subset=["twsa_cm"])
        if not observed_map_values.empty:
            wettest = observed_map_values.loc[observed_map_values["twsa_cm"].idxmax()]
            driest = observed_map_values.loc[observed_map_values["twsa_cm"].idxmin()]
            c1, c2, c3 = st.columns(3)
            c1.metric("Basins with data", f"{len(observed_map_values)} / 22")
            c2.metric(
                "Highest basin TWSA",
                f"{wettest['twsa_cm']:.2f} cm",
                help=str(wettest["MBASIN_E"]),
            )
            c3.metric(
                "Lowest basin TWSA",
                f"{driest['twsa_cm']:.2f} cm",
                help=str(driest["MBASIN_E"]),
            )

        st.caption(
            "This first web version maps basin-averaged TWSA from the processed 22-basin table. "
            "It is not yet the native GRACE pixel raster map."
        )


# ============================================================
# TAB 3 — SEASONAL CYCLE
# ============================================================
with tab_season:
    st.subheader(f"Seasonal TWSA cycle — {selected_name}")

    if selected_code == "NATIONAL":
        seasonal_source = (
            selected_series.dropna(subset=["twsa_cm"])
            .assign(calendar_month=lambda x: x["month_date"].dt.month)
            .groupby("calendar_month", as_index=False)
            .agg(
                mean_twsa_cm=("twsa_cm", "mean"),
                number_of_observations=("twsa_cm", "count"),
            )
        )
        seasonal_source["month_name"] = seasonal_source["calendar_month"].apply(
            lambda month: calendar.month_abbr[int(month)]
        )
    else:
        seasonal_source = clim_df.loc[clim_df["MB_CODE"] == selected_code].copy()

    seasonal_source = seasonal_source.sort_values("calendar_month")

    season_figure = go.Figure()
    season_figure.add_trace(
        go.Scatter(
            x=seasonal_source["month_name"],
            y=seasonal_source["mean_twsa_cm"],
            mode="lines+markers",
            name="Mean monthly TWSA",
        )
    )
    season_figure.add_hline(y=0, line_dash="dash")
    season_figure.update_layout(
        xaxis_title="Calendar month",
        yaxis_title="Mean TWSA (cm)",
        height=480,
        legend_title_text="",
    )
    st.plotly_chart(season_figure, use_container_width=True)

    if selected_code != "NATIONAL":
        summary_row = seasonal_df.loc[seasonal_df["MB_CODE"] == selected_code]
        if not summary_row.empty:
            row = summary_row.iloc[0]
            c1, c2, c3 = st.columns(3)
            c1.metric("Highest storage month", str(row["highest_storage_month"]))
            c1.caption(f"Mean TWSA: {row['highest_mean_twsa_cm']:.2f} cm")
            c2.metric("Lowest storage month", str(row["lowest_storage_month"]))
            c2.caption(f"Mean TWSA: {row['lowest_mean_twsa_cm']:.2f} cm")
            c3.metric("Seasonal amplitude", f"{row['seasonal_amplitude_cm']:.2f} cm")

    st.markdown("#### All-basin monthly climatology")
    heatmap_table = (
        clim_df.pivot(index="MBASIN_E", columns="calendar_month", values="mean_twsa_cm")
        .reindex(columns=range(1, 13))
    )

    heatmap_figure = go.Figure(
        data=go.Heatmap(
            z=heatmap_table.values,
            x=[calendar.month_abbr[month] for month in range(1, 13)],
            y=heatmap_table.index.tolist(),
            zmid=0,
            colorbar={"title": "TWSA (cm)"},
            hovertemplate="Basin: %{y}<br>Month: %{x}<br>Mean TWSA: %{z:.3f} cm<extra></extra>",
        )
    )
    heatmap_figure.update_layout(
        xaxis_title="Calendar month",
        yaxis_title="Principal river basin",
        height=720,
    )
    st.plotly_chart(heatmap_figure, use_container_width=True)


# ============================================================
# TAB 4 — TREND ANALYSIS
# ============================================================
with tab_trend:
    st.subheader("Long-term GRACE/GRACE-FO TWSA trends")
    st.caption(
        "Basin trend results are the precomputed Objective 1 outputs using observed months only: "
        "ordinary least squares, Mann-Kendall, and Sen's slope."
    )

    trend_plot = trend_df.sort_values("sen_slope_cm_per_year", ascending=True).copy()

    trend_figure = px.bar(
        trend_plot,
        x="sen_slope_cm_per_year",
        y="MBASIN_E",
        orientation="h",
        hover_data={
            "MB_CODE": True,
            "sen_slope_mm_per_year": ":.3f",
            "mann_kendall_p_value": ":.4g",
            "mann_kendall_trend": True,
        },
        labels={
            "sen_slope_cm_per_year": "Sen's slope (cm/year)",
            "MBASIN_E": "Principal river basin",
        },
        title="Sen's slope for Thailand's 22 principal river basins",
    )
    trend_figure.add_vline(x=0, line_dash="dash")
    trend_figure.update_layout(height=760)
    st.plotly_chart(trend_figure, use_container_width=True)

    significant_count = int((trend_df["mann_kendall_p_value"] < 0.05).sum())
    decreasing_count = int((trend_df["sen_slope_cm_per_year"] < 0).sum())
    increasing_count = int((trend_df["sen_slope_cm_per_year"] > 0).sum())

    c1, c2, c3 = st.columns(3)
    c1.metric("Significant MK trends (p < 0.05)", significant_count)
    c2.metric("Basins with negative Sen's slope", decreasing_count)
    c3.metric("Basins with positive Sen's slope", increasing_count)

    display_columns = [
        "MB_CODE",
        "MBASIN_E",
        "number_of_observations",
        "sen_slope_cm_per_year",
        "sen_slope_mm_per_year",
        "mann_kendall_trend",
        "mann_kendall_p_value",
        "ols_slope_cm_per_year",
        "ols_p_value",
        "ols_r_squared",
    ]
    display_columns = [column for column in display_columns if column in trend_df.columns]
    st.dataframe(
        trend_df[display_columns].sort_values("sen_slope_cm_per_year"),
        use_container_width=True,
        hide_index=True,
    )

    st.warning(
        "Trend statistics describe observed TWSA behavior. They do not by themselves identify whether a trend is caused by climate or human activity."
    )


# ============================================================
# TAB 5 — DATA
# ============================================================
with tab_data:
    st.subheader("Download Objective 1 dashboard data")

    selected_download = selected_series.copy()
    if selected_code == "NATIONAL":
        selected_filename = "Thailand_National_GRACE_TWSA_dashboard.csv"
    else:
        selected_filename = f"GRACE_TWSA_Basin_{selected_code}.csv"

    st.download_button(
        "Download selected location time series",
        data=csv_bytes(selected_download),
        file_name=selected_filename,
        mime="text/csv",
    )

    st.download_button(
        "Download 22-basin trend results",
        data=csv_bytes(trend_df),
        file_name=TREND_FILE.name,
        mime="text/csv",
    )

    st.download_button(
        "Download monthly basin climatology",
        data=csv_bytes(clim_df),
        file_name=CLIM_FILE.name,
        mime="text/csv",
    )

    st.download_button(
        "Download seasonal basin summary",
        data=csv_bytes(seasonal_df),
        file_name=SEASONAL_FILE.name,
        mime="text/csv",
    )

    st.markdown("#### Files used by this app")
    st.code(
        "\n".join(
            [
                "data/Thailand_National_GRACE_TimeSeries_CompleteTimeline.csv",
                "data/Thailand_22_Basins_Complete_Monthly_Timeline.csv",
                "data/Thailand_22_Basins_TWSA_Trend_Results.csv",
                "data/Thailand_22_Basins_Monthly_TWSA_Climatology.csv",
                "data/Thailand_22_Basins_Seasonal_TWSA_Summary.csv",
                "data/Thailand_22_Principal_Basins.gpkg",
            ]
        )
    )

    st.markdown("#### Methodological safeguards")
    st.markdown(
        "- Whole-Thailand study domain with 22 principal river basins.\n"
        "- Original GRACE/GRACE-FO missing months remain missing.\n"
        "- No interpolation is applied in the dashboard.\n"
        "- The 12-month moving average is for visualization only.\n"
        "- Formal basin trends use observed months only.\n"
        "- Climate-versus-human attribution belongs to the later objectives and is not inferred from Objective 1 alone."
    )


st.markdown("---")
st.caption(
    "Thailand GRACE/GRACE-FO Objective 1 Decision Support System • Streamlit dashboard"
)
